name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Scan container images for vulnerabitilies using Lacework
      uses: timarenz/lw-scanner-action:v0.2.2
      env:
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          with:
            image_name: node
            image_tag: 12.18.2-alpine
            fail_if_critical_vulnerabilities_found: true
            fail_only_if_vulnerabilities_fixable: true
